{% set name = "importlab" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3893853b1f6eb027da509c3b40e6787e95dd66b4b66f1b3613aad77556e1465

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - networkx >=2
    - python >=3.6

test:
  imports:
    - importlab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/importlab
  summary: A library to calculate python dependency graphs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
    - ngam
