{% set name = "importlab" %}
{% set version = "0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b24b3aac3b073966ae42fb2d3a7764f3377b30bb72c0d411fe29134cc9276e86

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - networkx >=2
    - python >=3.6

test:
  imports:
    - importlab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/importlab
  summary: A library to calculate python dependency graphs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
